In [2]:
import pandas as pd
import numpy as np

In [4]:
file_path = r"C:\Users\Surya\OneDrive\Desktop\Housekeeping Agent (RTD project)\data\raw\case 2 tripadvisor tm.xlsx"

xls = pd.ExcelFile(file_path)

print(xls.sheet_names)

['mdptmtopic', 'AssocRules_Output1', 'Regression']

In [5]:
df = pd.read_excel(
    file_path,
    sheet_name="mdptmtopic"
)

df.head()

,TextTopic_raw1,TextTopic_raw2,TextTopic_raw3,TextTopic_raw4,TextTopic_raw5,TextTopic_raw6,TextTopic_raw7,TextTopic_raw8,TextTopic_raw9,TextTopic_raw10,...,jun_aug,sep_nov,dec_feb,eng,jp,cn,hotel_photos,qna,room_tips,web_add
0,-0.010,0.022,0.007,0.017,0.010,0.036,0.007,0.005,0.017,0.004,...,631.0,579.0,730.0,2599.0,252.0,260.0,1564.0,30.0,622.0,https://www.tripadvisor.com.sg/Hotel_Review-g2...
1,0.042,0.008,0.021,-0.075,0.042,0.069,0.006,-0.005,0.014,0.034,...,631.0,579.0,730.0,2599.0,252.0,260.0,1564.0,30.0,622.0,https://www.tripadvisor.com.sg/Hotel_Review-g2...
2,0.017,0.054,0.047,-0.006,-0.013,0.099,0.014,0.005,0.010,0.042,...,631.0,579.0,730.0,2599.0,252.0,260.0,1564.0,30.0,622.0,https://www.tripadvisor.com.sg/Hotel_Review-g2...
3,0.013,0.002,-0.015,0.020,0.001,0.016,0.011,0.019,0.023,0.118,...,631.0,579.0,730.0,2599.0,252.0,260.0,1564.0,30.0,622.0,https://www.tripadvisor.com.sg/Hotel_Review-g2...
4,0.011,0.014,-0.008,0.002,-0.018,0.152,0.001,0.010,0.014,-0.020,...,631.0,579.0,730.0,2599.0,252.0,260.0,1564.0,30.0,622.0,https://www.tripadvisor.com.sg/Hotel_Review-g2...

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 6030
Columns: 63
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6030 entries, 0 to 6029
Data columns (total 63 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TextTopic_raw1    6030 non-null   float64
 1   TextTopic_raw2    6030 non-null   float64
 2   TextTopic_raw3    6030 non-null   float64
 3   TextTopic_raw4    6030 non-null   float64
 4   TextTopic_raw5    6030 non-null   float64
 5   TextTopic_raw6    6030 non-null   float64
 6   TextTopic_raw7    6030 non-null   float64
 7   TextTopic_raw8    6030 non-null   float64
 8   TextTopic_raw9    6030 non-null   float64
 9   TextTopic_raw10   6030 non-null   float64
 10  TextTopic_raw11   6030 non-null   float64
 11  TextTopic_raw12   6030 non-null   float64
 12  TextTopic_raw13   6030 non-null   float64
 13  TextTopic_raw14   6030 non-null   float64
 14  TextTopic_raw15   6030 non-null   float64
 15  TextTopic_raw16   6030 non-null   float64
 16  TextTopic_raw17   6030 non-null   float64
 17  TextTopic_raw18   6030 non-null   float64
 18  TextTopic_raw19   6030 non-null   float64
 19  TextTopic_raw20   6030 non-null   float64
 20  TextTopic_raw21   6030 non-null   float64
 21  TextTopic_raw22   6030 non-null   float64
 22  TextTopic_raw23   6030 non-null   float64
 23  TextTopic_raw24   6030 non-null   float64
 24  TextTopic_raw25   6030 non-null   float64
 25  _DOCUMENT_        6030 non-null   int64
 26  name              5996 non-null   object
 27  location          5305 non-null   object
 28  level             5054 non-null   float64
 29  no_reviews        5996 non-null   float64
 30  no_hotel_reviews  4682 non-null   float64
 31  no_help_vote      5340 non-null   float64
 32  title             6009 non-null   object
 33  rating            6030 non-null   int64
 34  review_date       6030 non-null   datetime64[ns]
 35  review_content    6009 non-null   object
 36  url               6029 non-null   object
 37  hotel_id          6029 non-null   object
 38  hotel_name        6029 non-null   object
 39  hotel_no_reviews  6029 non-null   float64
 40  hotel_rank        6029 non-null   float64
 41  address           6029 non-null   object
 42  excellent         6029 non-null   float64
 43  very_good         6029 non-null   float64
 44  average           6029 non-null   float64
 45  poor              6029 non-null   float64
 46  terrible          6029 non-null   float64
 47  families          6029 non-null   float64
 48  couples           6029 non-null   float64
 49  solo              6029 non-null   float64
 50  business          6029 non-null   float64
 51  friends           6029 non-null   float64
 52  mar_may           6029 non-null   float64
 53  jun_aug           6029 non-null   float64
 54  sep_nov           6029 non-null   float64
 55  dec_feb           6029 non-null   float64
 56  eng               6029 non-null   float64
 57  jp                2725 non-null   float64
 58  cn                6029 non-null   float64
 59  hotel_photos      6029 non-null   float64
 60  qna               6029 non-null   float64
 61  room_tips         6029 non-null   float64
 62  web_add           6029 non-null   object
dtypes: datetime64[ns](1), float64(51), int64(2), object(9)
memory usage: 2.9+ MB

In [7]:
df.columns.tolist()

['TextTopic_raw1',
 'TextTopic_raw2',
 'TextTopic_raw3',
 'TextTopic_raw4',
 'TextTopic_raw5',
 'TextTopic_raw6',
 'TextTopic_raw7',
 'TextTopic_raw8',
 'TextTopic_raw9',
 'TextTopic_raw10',
 'TextTopic_raw11',
 'TextTopic_raw12',
 'TextTopic_raw13',
 'TextTopic_raw14',
 'TextTopic_raw15',
 'TextTopic_raw16',
 'TextTopic_raw17',
 'TextTopic_raw18',
 'TextTopic_raw19',
 'TextTopic_raw20',
 'TextTopic_raw21',
 'TextTopic_raw22',
 'TextTopic_raw23',
 'TextTopic_raw24',
 'TextTopic_raw25',
 '_DOCUMENT_',
 'name',
 'location',
 'level',
 'no_reviews',
 'no_hotel_reviews',
 'no_help_vote',
 'title',
 'rating',
 'review_date',
 'review_content',
 'url',
 'hotel_id',
 'hotel_name',
 'hotel_no_reviews',
 'hotel_rank',
 'address',
 'excellent',
 'very_good',
 'average',
 'poor',
 'terrible',
 'families',
 'couples',
 'solo',
 'business',
 'friends',
 'mar_may',
 'jun_aug',
 'sep_nov',
 'dec_feb',
 'eng',
 'jp',
 'cn',
 'hotel_photos',
 'qna',
 'room_tips',
 'web_add']

In [8]:
df.shape

(6030, 63)

In [9]:
housekeeping_df = df.copy()

In [10]:
keep_cols = [
    'hotel_id',
    'hotel_name',
    'hotel_rank',
    'hotel_no_reviews',
    'rating',
    'review_date',
    'review_content',
    'excellent',
    'very_good',
    'average',
    'poor',
    'terrible',
    'families',
    'couples',
    'solo',
    'business',
    'friends'
]

housekeeping_df = housekeeping_df[keep_cols]

housekeeping_df.head()

,hotel_id,hotel_name,hotel_rank,hotel_no_reviews,rating,review_date,review_content,excellent,very_good,average,poor,terrible,families,couples,solo,business,friends
0,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-09,The rooms in the Intercontinental Hotel are be...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0
1,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-07,Really enjoyed every aspect of this hotel The...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0
2,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-06,My husband and I love visiting the Intercon in...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0
3,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-03,Great buffet breakfast spacious room and beau...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0
4,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-03,This is my 3rd stay at the InterContinental an...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0

In [11]:
housekeeping_df.isnull().sum()

hotel_id             1
hotel_name           1
hotel_rank           1
hotel_no_reviews     1
rating               0
review_date          0
review_content      21
excellent            1
very_good            1
average              1
poor                 1
terrible             1
families             1
couples              1
solo                 1
business             1
friends              1
dtype: int64

In [12]:
housekeeping_df = housekeeping_df.drop_duplicates()

print(housekeeping_df.shape)

(6028, 17)

In [13]:
housekeeping_df.isnull().sum()

hotel_id             1
hotel_name           1
hotel_rank           1
hotel_no_reviews     1
rating               0
review_date          0
review_content      19
excellent            1
very_good            1
average              1
poor                 1
terrible             1
families             1
couples              1
solo                 1
business             1
friends              1
dtype: int64

In [14]:
housekeeping_df = housekeeping_df.dropna(
    subset=["review_content"]
)

housekeeping_df = housekeeping_df.fillna(0)

print(housekeeping_df.shape)

(6009, 17)

In [15]:
housekeeping_df.isnull().sum().sum()

np.int64(0)

In [16]:
housekeeping_df["room_id"] = np.random.randint(
    100,
    999,
    size=len(housekeeping_df)
)

In [17]:
housekeeping_df["room_id"] = range(
    1000,
    1000 + len(housekeeping_df)
)

In [18]:
housekeeping_df.head()

,hotel_id,hotel_name,hotel_rank,hotel_no_reviews,rating,review_date,review_content,excellent,very_good,average,poor,terrible,families,couples,solo,business,friends,room_id
0,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-09,The rooms in the Intercontinental Hotel are be...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1000
1,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-07,Really enjoyed every aspect of this hotel The...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1001
2,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-06,My husband and I love visiting the Intercon in...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1002
3,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-03,Great buffet breakfast spacious room and beau...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1003
4,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-03,This is my 3rd stay at the InterContinental an...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1004

In [19]:
housekeeping_df.shape

(6009, 18)

In [20]:
housekeeping_df.columns.tolist()

['hotel_id',
 'hotel_name',
 'hotel_rank',
 'hotel_no_reviews',
 'rating',
 'review_date',
 'review_content',
 'excellent',
 'very_good',
 'average',
 'poor',
 'terrible',
 'families',
 'couples',
 'solo',
 'business',
 'friends',
 'room_id']

In [21]:
print(housekeeping_df.shape)
housekeeping_df.head(2)

(6009, 18)

,hotel_id,hotel_name,hotel_rank,hotel_no_reviews,rating,review_date,review_content,excellent,very_good,average,poor,terrible,families,couples,solo,business,friends,room_id
0,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-09,The rooms in the Intercontinental Hotel are be...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1000
1,g294265-d299199,InterContinental Singapore,17.0,3102.0,5,2016-04-07,Really enjoyed every aspect of this hotel The...,1615.0,712.0,189.0,62.0,21.0,539.0,864.0,198.0,738.0,152.0,1001

In [22]:
complaint_keywords = [
    "dirty",
    "unclean",
    "dust",
    "stain",
    "smell",
    "housekeeping",
    "cleaning",
    "filthy",
    "bathroom",
    "toilet"
]

housekeeping_df["complaint_flag"] = (
    housekeeping_df["review_content"]
    .astype(str)
    .str.lower()
    .apply(
        lambda text: int(
            any(word in text for word in complaint_keywords)
        )
    )
)

print("Done")

Done

In [23]:
housekeeping_df["complaint_flag"].value_counts()

complaint_flag
0    4781
1    1228
Name: count, dtype: int64

In [24]:
def assign_priority(rating):

    if rating <= 2:
        return "High"

    elif rating == 3:
        return "Medium"

    else:
        return "Low"


housekeeping_df["housekeeping_priority"] = (
    housekeeping_df["rating"]
    .apply(assign_priority)
)

housekeeping_df["housekeeping_priority"].value_counts()

housekeeping_priority
Low       5115
Medium     592
High       302
Name: count, dtype: int64

In [25]:
housekeeping_df["cleaning_demand_score"] = (
    housekeeping_df["poor"]
    + housekeeping_df["terrible"]
    - (0.5 * housekeeping_df["excellent"])
)

housekeeping_df["cleaning_demand_score"].describe()

count    6009.000000
mean     -382.439091
std       304.674497
min      -724.500000
25%      -724.500000
50%      -343.500000
75%       -64.500000
max         0.000000
Name: cleaning_demand_score, dtype: float64

In [26]:
guest_cols = [
    "families",
    "couples",
    "solo",
    "business",
    "friends"
]

housekeeping_df["dominant_guest_type"] = (
    housekeeping_df[guest_cols]
    .idxmax(axis=1)
)

housekeeping_df["dominant_guest_type"].value_counts()

dominant_guest_type
couples     3015
families    2854
business     140
Name: count, dtype: int64

In [27]:
np.random.seed(42)

housekeeping_df["room_status"] = np.where(
    housekeeping_df["complaint_flag"] == 1,
    "Dirty",
    "Clean"
)

housekeeping_df["checkout_hour"] = np.random.randint(
    6,
    12,
    size=len(housekeeping_df)
)

housekeeping_df["estimated_cleaning_time"] = np.where(
    housekeeping_df["room_status"] == "Dirty",
    np.random.randint(30, 60, size=len(housekeeping_df)),
    np.random.randint(10, 20, size=len(housekeeping_df))
)

In [28]:
housekeeping_df.columns.tolist()

['hotel_id',
 'hotel_name',
 'hotel_rank',
 'hotel_no_reviews',
 'rating',
 'review_date',
 'review_content',
 'excellent',
 'very_good',
 'average',
 'poor',
 'terrible',
 'families',
 'couples',
 'solo',
 'business',
 'friends',
 'room_id',
 'complaint_flag',
 'housekeeping_priority',
 'cleaning_demand_score',
 'dominant_guest_type',
 'room_status',
 'checkout_hour',
 'estimated_cleaning_time']

In [33]:
housekeeping_df.to_csv(
    r"c:\Users\Surya\OneDrive\Desktop\Housekeeping Agent (RTD project)\data\processed\housekeeping_dataset.csv",
    index=False
)

print("Saved successfully")

Saved successfully